#!/bin/sh

# Use the "logo" key as the primary modifier
mod="Mod4"
mod1="Mod1"

# Environment Setup
riverctl spawn "dbus-update-activation-environment SEATD_SOCK DISPLAY WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=river"

# --- General Mappings ---
riverctl map normal $mod Return spawn foot
riverctl map normal $mod B spawn "killall -SIGUSR1 waybar"
riverctl map normal $mod C spawn "rofi -show drun -show-icons -display-drun 'Search'"
riverctl map normal $mod Y spawn "~/.config/river/scripts/yt"
riverctl map normal $mod+Shift C spawn "dmenu_run"
riverctl map normal $mod W spawn woomer
riverctl map normal $mod+Shift D spawn "discord --ignore-gpu-blocklist --disable-features=UseOzonePlatform --enable-features=VaapiVideoDecoder --use-gl=desktop --enable-gpu-rasterization --enable-zero-copy"
riverctl map normal $mod+Shift L spawn "swaylock -i ~/.dotfiles/.assets/wallpapers/archlinux.png"
riverctl map normal $mod+Shift R spawn "~/.config/river/init"
riverctl map normal $mod Q close
riverctl map normal $mod+Shift Q exit
riverctl map normal $mod+$mod1 Q spawn "shutdown now"

# --- Output Management ---
riverctl map normal $mod O focus-output next
riverctl map normal $mod+Shift O send-to-output next

# --- View Management ---
riverctl map normal $mod J focus-view next
riverctl map normal $mod K focus-view previous
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# --- Layout Control (rivertile) ---
# Note: In newer versions, we pass the command directly
riverctl map normal $mod H send-layout-cmd rivertile main-ratio -0.05
riverctl map normal $mod L send-layout-cmd rivertile main-ratio +0.05
riverctl map normal $mod+Mod1 H send-layout-cmd rivertile main-count +1
riverctl map normal $mod+Mod1 L send-layout-cmd rivertile main-count -1

# Layout orientation
riverctl map normal $mod+Shift+Mod1 K send-layout-cmd rivertile main-location top
riverctl map normal $mod+Shift+Mod1 L send-layout-cmd rivertile main-location right
riverctl map normal $mod+Shift+Mod1 J send-layout-cmd rivertile main-location bottom
riverctl map normal $mod+Shift+Mod1 H send-layout-cmd rivertile main-location left

# --- Floating and Tiling Control ---
riverctl map normal $mod F toggle-float
riverctl map normal $mod M toggle-fullscreen

# Move/Resize (Floating)
riverctl map normal $mod left move left 100
riverctl map normal $mod down move down 100
riverctl map normal $mod up move up 100
riverctl map normal $mod right move right 100

riverctl map normal $mod+Shift left resize horizontal -100
riverctl map normal $mod+Shift down resize vertical 100
riverctl map normal $mod+Shift up resize vertical -100
riverctl map normal $mod+Shift right resize horizontal 100

# Snap views
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# --- Pointer Mappings ---
riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

# --- Tags (1-7) ---
for i in $(seq 1 7)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
    riverctl map normal $mod+Control $i toggle-focused-tags $tags
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# All tags
all_tags=$(((1 << 32) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# --- Passthrough/Media Keys ---
for mode in normal locked
do
    riverctl map $mode None XF86AudioRaiseVolume  spawn 'amixer -D pulse set Master 5%+'
    riverctl map $mode None XF86AudioLowerVolume  spawn 'amixer -D pulse set Master 5%-'
    riverctl map $mode None XF86AudioMute          spawn 'amixer -D pulse set Master 1+ toggle'
    riverctl map $mode None XF86AudioMedia spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPlay  spawn 'playerctl play-pause'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'
    riverctl map $mode None XF86MonBrightnessUp   spawn 'brightnessctl set 5%+'
    riverctl map $mode None XF86MonBrightnessDown spawn 'brightnessctl set 5%-'
    riverctl map $mode None Print spawn "$HOME/.config/river/scripts/ss"
done

# --- Appearance & Behavior ---
riverctl border-color-focused 0x5e81ac
riverctl border-color-unfocused 0x4c566a
riverctl focus-follows-cursor normal

# Filters
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# --- Scratchpad ---
scratch_tag=$((1 << 20 ))
riverctl map normal $mod P toggle-focused-tags ${scratch_tag}
riverctl map normal $mod+Shift P set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}

# --- Background Processes ---
# Start the layout generator
rivertile -view-padding 5 -outer-padding 5 &
bash $HOME/.config/river/process.sh &

# --- GSettings/GTK Theme ---
gnome_schema="org.gnome.desktop.interface"
gsettings set "$gnome_schema" gtk-theme "Nordic"
gsettings set "$gnome_schema" icon-theme "Numigsur"
gsettings set "$gnome_schema" text-scaling-factor 1.33
