#!/bin/sh

# 1. Start the Lua Manager (The Brain)
riverctl spawn "river-luwm" &

# 2. Start the Layout Engine
riverctl spawn "rivertile -main-ratio 0.5 -view-padding 2 -outer-padding 2" &
riverctl output-layout rivertile

# 3. Run the Background Process script
sh "$HOME/.config/river/process.sh" &

# 4. Touchpad Config
for pad in $(riverctl list-inputs | grep -i touchpad); do
    riverctl input "$pad" events enabled
    riverctl input "$pad" tap enabled
done
