#!/bin/sh

# Clean up any lingering processes from previous sessions
pkill river-luwm

# Export critical Wayland environment variables
export XDG_CURRENT_DESKTOP=river
export XDG_SESSION_TYPE=wayland

# Execute the Lua Manager (This replaces all riverctl calls)
exec river-luwm
